# Relesae build
name: build

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
      - '.dockerignore'
    branches-ignore:
      - daily
    tags:
      - '*'
jobs:
  get_dep:
    strategy:
      matrix:
        platform:
        - os: windows-latest
        - os: macOS-11.0
        - os: ubuntu-20.04
    runs-on: ${{ matrix.platform.os }}
    steps:
    - run: |
        git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
        export PATH=${PATH}:./depot_tools
        gclient
        fetch --no-history --nohooks webrtc